---
- name: Yum updates Excluding Kernel
  gather_facts: false
  become: true
  become_user: root
  hosts: all
  tasks:
    - name: Upgrade all packages, excluding kernel packages
      yum:
        name: '*'
        state: latest
        exclude: kernel*
