---
- name: Load Balancer Status
  gather_facts: false
  hosts: all
  tasks:
    - name: Check current status
      shell: /usr/local/bin/lbstatus              
      register: command_output
    - debug:
       var: command_output.stdout_lines
       changed_when: false
