---
- name: Load Balancer Status
  gather_facts: false
  hosts: all
  tasks:
    - name: Check current status
      shell: /usr/local/bin/lbstatus              
      register: lbstatus
    - debug:
       var: lbstatus.stdout_lines
