---
- name: Load Balancer Status
  gather_facts: false
  become: yes
  hosts: plaporalb1
         
  tasks:
    - name: Switch Load Balancer
      shell: /usr/local/bin/lbswitch
      register: lbswitch
    - debug:  
        var: lbswitch.stdout_lines
